### ISSUE TITLE
long time no results return

### ISSUE THREAD

**Issue by Biaocsu** [ptrstn/deepl-translate#4]
I met a problem that it comes by chance and paused for a long time with no results.
I saw these code below, but didn't figure out what's the meaning of it:

![微信截图_20210106150035](https://user-images.githubusercontent.com/45280752/103741074-6734cd80-5033-11eb-820d-3643b202c41e.png)

**Comment by CoolCat467** [comment]
Well, it's generating a timestamp. I'm not quite sure what your problem is though. Code looks good. Sure, if you give it a ton of really long sentences, it might take a while to process it, but again, not sure what your problem is.

**Comment by ptrstn** [comment]
> I met a problem that it comes by chance and paused for a long time with no results.
> I saw these code below, but didn't figure out what's the meaning of it:
> 
> ![微信截图_20210106150035](https://user-images.githubusercontent.com/45280752/103741074-6734cd80-5033-11eb-820d-3643b202c41e.png)

This code was necessary to create a valid timestamp.

Currently the test cases still seem to work, so I will close this ticket.
