### ISSUE TITLE
 'charmap' codec can't decode byte 0x81

### ISSUE THREAD

**Issue by Arthurfogo7** [ptrstn/deepl-translate#5]
ERROR: Command errored out with exit status 1:
     command: 'C:\Python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\arthu\\AppData\\Local\\Temp\\pip-req-build-cstxngbn\\setup.py'"'"'; __file__='"'"'C:\\Users\\arthu\\AppData\\Local\\Temp\\pip-req-build-cstxngbn\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\arthu\AppData\Local\Temp\pip-pip-egg-info-nkf6bs41'
         cwd: C:\Users\arthu\AppData\Local\Temp\pip-req-build-cstxngbn\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\arthu\AppData\Local\Temp\pip-req-build-cstxngbn\setup.py", line 24, in <module>
        long_description = f.read()
      File "C:\Python39\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1284: character maps to <undefined>
    ----------------------------------------
WARNING: Discarding git+https://github.com/ptrstn/deepl-translate. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ptrstn** [comment]
What was the content of the file?

**Comment by Arthurfogo7** [comment]
This happened when I tried to install the file by "pip install git+https://github.com/ptrstn/deepl-translate"
C:\Users\arthu>pip install git+https://github.com/ptrstn/deepl-translate
Collecting git+https://github.com/ptrstn/deepl-translate
  Cloning https://github.com/ptrstn/deepl-translate to c:\users\arthu\appdata\local\temp\pip-req-build-ylfht7ag
  Running command git clone -q https://github.com/ptrstn/deepl-translate 'C:\Users\arthu\AppData\Local\Temp\pip-req-build-ylfht7ag'
  Resolved https://github.com/ptrstn/deepl-translate to commit 8588737a9df73bc0edf1c3f5e26305bed749e2d0
    ERROR: Command errored out with exit status 1:
 command: 'C:\Python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\arthu\\AppData\\Local\\Temp\\pip-req-build-ylfht7ag\\setup.py'"'"'; __file__='"'"'C:\\Users\\arthu\\AppData\\Local\\Temp\\pip-req-build-ylfht7ag\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\arthu\AppData\Local\Temp\pip-pip-egg-info-oo665ktp'

**Comment by Laserlicht** [comment]
#6 solves this issue
