### ISSUE TITLE
Update supported languages

### ISSUE THREAD

**Issue by ptrstn** [ptrstn/deepl-translate#7]
Currently only the following languages are supported by this tool:

| Abbreviation | Language   | Writing in own language |
|--------------|------------|-------------------------|
| DE           | German     | Deutsch                 |
| EN           | English    | English                 |
| FR           | French     | français                |
| ES           | Spanish    | español                 |
| PT           | Portuguese | português               |
| IT           | Italian    | italiano                |
| NL           | Dutch      | Nederlands              |
| PL           | Polish     | polski                  |
| RU           | Russian    | русский                 |
| JA           | Japanese   | 日本語                   |
| ZH           | Chinese    | 中文                     |

But DeepL now supports many more languages like swedish, finish and estonian.
The list of supported languages should be updated and the tool then tested accordingly.

**Comment by Erick-vital** [comment]
which files do i have to change ?

**Comment by ptrstn** [comment]
> which files do i have to change ?

```deepl/settings.py```

every new entry should be tested (both abbreviation ```code``` and ```language```)

**Comment by ptrstn** [comment]
Supported languages, extracted from deepl.com:

```html
<select class="lmt__language_select__mobileLangSelect __web-inspector-hide-shortcut__">
   <option value="{&quot;lang&quot;:&quot;auto&quot;}">Any language (detect)</option>
   <option value="{&quot;lang&quot;:&quot;BG&quot;}">Bulgarian</option>
   <option value="{&quot;lang&quot;:&quot;ZH&quot;}">Chinese</option>
   <option value="{&quot;lang&quot;:&quot;CS&quot;}">Czech</option>
   <option value="{&quot;lang&quot;:&quot;DA&quot;}">Danish</option>
   <option value="{&quot;lang&quot;:&quot;NL&quot;}">Dutch</option>
   <option value="{&quot;lang&quot;:&quot;EN&quot;}">English</option>
   <option value="{&quot;lang&quot;:&quot;ET&quot;}">Estonian</option>
   <option value="{&quot;lang&quot;:&quot;FI&quot;}">Finnish</option>
   <option value="{&quot;lang&quot;:&quot;FR&quot;}">French</option>
   <option value="{&quot;lang&quot;:&quot;DE&quot;}">German</option>
   <option value="{&quot;lang&quot;:&quot;EL&quot;}">Greek</option>
   <option value="{&quot;lang&quot;:&quot;HU&quot;}">Hungarian</option>
   <option value="{&quot;lang&quot;:&quot;IT&quot;}">Italian</option>
   <option value="{&quot;lang&quot;:&quot;JA&quot;}">Japanese</option>
   <option value="{&quot;lang&quot;:&quot;LV&quot;}">Latvian</option>
   <option value="{&quot;lang&quot;:&quot;LT&quot;}">Lithuanian</option>
   <option value="{&quot;lang&quot;:&quot;PL&quot;}">Polish</option>
   <option value="{&quot;lang&quot;:&quot;PT&quot;}">Portuguese</option>
   <option value="{&quot;lang&quot;:&quot;RO&quot;}">Romanian</option>
   <option value="{&quot;lang&quot;:&quot;RU&quot;}">Russian</option>
   <option value="{&quot;lang&quot;:&quot;SK&quot;}">Slovak</option>
   <option value="{&quot;lang&quot;:&quot;SL&quot;}">Slovenian</option>
   <option value="{&quot;lang&quot;:&quot;ES&quot;}">Spanish</option>
   <option value="{&quot;lang&quot;:&quot;SV&quot;}">Swedish</option>
</select>
```

This leads to following list of supported languages: 

```
BG Bulgarian
ZH Chinese
CS Czech
DA Danish
NL Dutch
EN English
ET Estonian
FI Finnish
FR French
DE German
EL Greek
HU Hungarian
IT Italian
JA Japanese
LV Latvian
LT Lithuanian
PL Polish
PT Portuguese
RO Romanian
RU Russian
SK Slovak
SL Slovenian
ES Spanish
SV Swedish
```

With the help of [Tables Generator](https://www.tablesgenerator.com/markdown_tables), the previous information and the [List of language names](https://meta.wikimedia.org/wiki/Template:List_of_language_names_ordered_by_code), the following table can be generated:

| Abbreviation | Language   | Writing in own language |
|--------------|------------|-------------------------|
| BG           | Bulgarian  | Български               |
| ZH           | Chinese    | 中文                    |
| CS           | Czech      | Česky                   |
| DA           | Danish     | Dansk                   |
| NL           | Dutch      | Nederlands              |
| EN           | English    | English                 |
| ET           | Estonian   | Eesti                   |
| FI           | Finnish    | Suomi                   |
| FR           | French     | Français                |
| DE           | German     | Deutsch                 |
| EL           | Greek      | Ελληνικά                |
| HU           | Hungarian  | Magyar                  |
| IT           | Italian    | Italiano                |
| JA           | Japanese   | 日本語                  |
| LV           | Latvian    | Latviešu                |
| LT           | Lithuanian | Lietuvių                |
| PL           | Polish     | Polski                  |
| PT           | Portuguese | Português               |
| RO           | Romanian   | Română                  |
| RU           | Russian    | Русский                 |
| SK           | Slovak     | Slovenčina              |
| SL           | Slovenian  | Slovenščina             |
| ES           | Spanish    | Español                 |
| SV           | Swedish    | Svenska                 |
